# -*- coding: utf-8 -*-
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Alexa skill handler powered by Google Gemini generative AI.

This module implements an AWS Lambda handler for an Amazon Alexa skill that uses
the Google Generative AI (Gemini) model to answer user questions.

To deploy this as an Alexa skill:
1. Create a new Alexa skill in the Alexa Developer Console.
2. Set the endpoint to an AWS Lambda function running this handler.
3. Add an ``AskQuestionIntent`` intent with a required ``query`` slot of type
   ``AMAZON.SearchQuery``.
4. Set the ``GOOGLE_API_KEY`` environment variable in the Lambda configuration.
"""

import json
import logging
import os
from typing import Any

import google.generativeai as genai

logger = logging.getLogger(__name__)

_LAUNCH_WELCOME = (
    "Welcome to Gemini AI assistant. You can ask me any question. "
    "For example, say: ask Gemini, what is the speed of light?"
)
_LAUNCH_REPROMPT = "What would you like to know?"
_HELP_TEXT = (
    "You can ask me any question and I will use Google Gemini AI to answer it. "
    "For example, say: ask Gemini, how do I bake a chocolate cake?"
)
_FALLBACK_TEXT = (
    "Sorry, I didn't understand that. You can ask me any question. "
    "What would you like to know?"
)
_STOP_TEXT = "Goodbye!"
_ERROR_TEXT = "Sorry, I had trouble answering that. Please try again."


def _build_response(
    output_speech_text: str,
    *,
    reprompt_text: str | None = None,
    should_end_session: bool = True,
    card_title: str = "Gemini AI",
    card_content: str | None = None,
) -> dict[str, Any]:
    """Build an Alexa skill response dict.

    Args:
        output_speech_text: The text Alexa speaks to the user.
        reprompt_text: Optional text for the reprompt if the user doesn't respond.
        should_end_session: Whether to end the session after speaking.
        card_title: Title shown on the Alexa companion app card.
        card_content: Body text shown on the Alexa companion app card.

    Returns:
        A dict formatted as an Alexa skill response.
    """
    response: dict[str, Any] = {
        "outputSpeech": {
            "type": "PlainText",
            "text": output_speech_text,
        },
        "card": {
            "type": "Simple",
            "title": card_title,
            "content": card_content if card_content is not None else output_speech_text,
        },
        "shouldEndSession": should_end_session,
    }
    if reprompt_text is not None:
        response["reprompt"] = {
            "outputSpeech": {
                "type": "PlainText",
                "text": reprompt_text,
            }
        }
    return {"version": "1.0", "response": response}


def _get_query_from_intent(intent: dict[str, Any]) -> str | None:
    """Extract the query string from an Alexa intent's slots.

    Args:
        intent: The ``intent`` dict from the Alexa request.

    Returns:
        The slot value for the ``query`` slot, or ``None`` if not found.
    """
    slots = intent.get("slots", {})
    query_slot = slots.get("query", {})
    return query_slot.get("value")


def _ask_gemini(query: str, api_key: str | None = None) -> str:
    """Send *query* to the Gemini model and return the generated text.

    Args:
        query: The user's question or request.
        api_key: Optional API key. Falls back to the ``GOOGLE_API_KEY``
            environment variable when not provided.

    Returns:
        The text generated by Gemini.

    Raises:
        ValueError: If no API key is available.
    """
    # [START alexa_generative_ask_gemini]
    resolved_key = api_key or os.environ.get("GOOGLE_API_KEY")
    if not resolved_key:
        raise ValueError(
            "A Google API key is required. Set the GOOGLE_API_KEY environment "
            "variable or pass api_key explicitly."
        )
    genai.configure(api_key=resolved_key)
    model = genai.GenerativeModel("gemini-1.5-flash")
    response = model.generate_content(query)
    return response.text
    # [END alexa_generative_ask_gemini]


def _handle_launch_request() -> dict[str, Any]:
    return _build_response(
        _LAUNCH_WELCOME,
        reprompt_text=_LAUNCH_REPROMPT,
        should_end_session=False,
    )


def _handle_ask_question_intent(intent: dict[str, Any]) -> dict[str, Any]:
    """Handle an ``AskQuestionIntent`` by querying Gemini."""
    query = _get_query_from_intent(intent)
    if not query:
        return _build_response(
            _FALLBACK_TEXT,
            reprompt_text=_LAUNCH_REPROMPT,
            should_end_session=False,
        )
    try:
        answer = _ask_gemini(query)
        return _build_response(answer, card_title="Gemini AI", card_content=answer)
    except Exception:
        logger.exception("Error querying Gemini for query: %r", query)
        return _build_response(_ERROR_TEXT)


def _handle_help_intent() -> dict[str, Any]:
    return _build_response(
        _HELP_TEXT,
        reprompt_text=_LAUNCH_REPROMPT,
        should_end_session=False,
    )


def _handle_stop_or_cancel_intent() -> dict[str, Any]:
    return _build_response(_STOP_TEXT)


def _handle_fallback_intent() -> dict[str, Any]:
    return _build_response(
        _FALLBACK_TEXT,
        reprompt_text=_LAUNCH_REPROMPT,
        should_end_session=False,
    )


def _handle_session_ended_request() -> dict[str, Any]:
    return {"version": "1.0", "response": {}}


def _dispatch_intent(intent: dict[str, Any]) -> dict[str, Any]:
    """Route an IntentRequest to the appropriate handler."""
    intent_name = intent.get("name", "")
    if intent_name == "AskQuestionIntent":
        return _handle_ask_question_intent(intent)
    if intent_name == "AMAZON.HelpIntent":
        return _handle_help_intent()
    if intent_name in ("AMAZON.StopIntent", "AMAZON.CancelIntent"):
        return _handle_stop_or_cancel_intent()
    if intent_name == "AMAZON.FallbackIntent":
        return _handle_fallback_intent()
    return _build_response(
        _FALLBACK_TEXT,
        reprompt_text=_LAUNCH_REPROMPT,
        should_end_session=False,
    )


def lambda_handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """AWS Lambda entry point for the Alexa skill.

    Args:
        event: The Alexa skill request payload as a dict.
        context: The Lambda context object (unused).

    Returns:
        An Alexa skill response dict.
    """
    logger.info("Received event: %s", json.dumps(event))
    request = event.get("request", {})
    request_type = request.get("type", "")

    if request_type == "LaunchRequest":
        return _handle_launch_request()
    if request_type == "IntentRequest":
        return _dispatch_intent(request.get("intent", {}))
    if request_type == "SessionEndedRequest":
        return _handle_session_ended_request()

    return _build_response(_FALLBACK_TEXT)
